name: Build Tauri App for Windows

on:
  push:
    branches: [ master ]  # 或 main，根据你的默认分支

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          npm run tauri build

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Tauri-Windows-Exe
          path: src-tauri/target/release/*.exe
